![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [2]:
my_array = np.arange(10)
print(my_array[my_array%2 !=0][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [11]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [13]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [20]:
my_array = np.arange(1,21).reshape(4,5)
print(my_array)
print(my_array.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
my_array_sub= my_array[:2, :2]
print(my_array_sub)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [30]:
my_array_sub= my_array[::2, ::2]
print(my_array_sub)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [42]:
my_array_sub= my_array[:3:1, ::-1]
print(my_array_sub)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [48]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[x == "Loro"])


['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [55]:
my_array = np.arange(1,21).reshape(5,4)
upper, lower = np.hsplit(my_array, [2])
print(upper)
print(lower)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [60]:
my_array = np.arange(1,21).reshape(4,5)
print(my_array[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [67]:
zeros = np.zeros(10)
print(np.zeros(10).nbytes)
zeros[3] = 1
print(zeros)

80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [71]:
my_array = np.arange(10,50)
print(my_array[::-1])
print(my_array.reshape(-1,1))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [74]:
vector = np.array([1, 2, 0, 0, 4, 0])

indices_no_cero = np.nonzero(vector)[0]
print(indices_no_cero)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [75]:
matrix_random = np.random.rand(10,10)
print(matrix_random.min())
print(matrix_random.max())

0.0007137258005359692
0.9946936589571057


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [82]:
matrix_random = np.random.rand(30)
print(matrix_random.mean())

0.5150247841867793


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [242]:
matriz = np.zeros((5, 5), dtype=int)

# Rellenar los bordes con 1s
matriz[::4] = 1  # Primera y ultima fila 
matriz.T[::4] = 1  # Primera y ultima columna


print(matriz)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [237]:
matriz = np.ones((7,7),dtype=int)
matriz[1:-1,1:-1] = 0
print(matriz)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [243]:
matriz = np.zeros((8, 8), dtype=int)
matriz[::2, 1::2] = 1
matriz[1::2, ::2] = 1

print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [91]:
patron = np.array([[0, 1], [1, 0]])

matriz = np.tile(patron, (4, 4))

print(matriz)
                           

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [92]:
matrix_random = np.random.rand(5,5)
print((matrix_random - matrix_random.mean())/ matrix_random.std())

[[ 1.06285037  0.90577089 -0.97406338 -0.36458547  1.67880485]
 [ 0.08180034  1.21468665 -1.55315235 -1.44688389 -0.37856037]
 [-1.40325587  0.17951649  0.09200197 -0.78433378 -0.56446297]
 [-0.40641235 -0.48553612  0.68249254 -1.1596792   1.77676203]
 [ 0.83307141 -1.25090057  1.45516592  0.36504732  0.44385552]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [97]:
my_array = np.arange(11)
my_array2 = np.where((3 < my_array) & (my_array < 8), -1, my_array)
print(my_array2)
my_array2 = np.where((3 < my_array) & (my_array < 8), - my_array, my_array)
print(my_array2)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [8]:
import numpy as np
# Crear un tablero vacío de 10x10 lleno de espacios en blanco
tablero = np.full((10, 10), " ")

# Posiciones de los barcos iniciales
barcos = [[(0, 1), (1, 1)], [(1, 3), (1, 4), (1, 5), (1, 6)]]

# Función para posicionar un barco en el tablero
def posicionar_barco(barco):
    for posicion in barco:
        tablero[posicion[0], posicion[1]] = "O"

# Posicionar los barcos iniciales en el tablero
for barco in barcos:
    posicionar_barco(barco)

# Función para realizar un disparo en el tablero
def disparo(disparo):
    for barco in barcos:
        for posicion in barco:
            if posicion == disparo:
                tablero[disparo[0], disparo[1]] = "X"
            elif posicion != disparo and tablero[disparo[0], disparo[1]] == " ":
                tablero[disparo[0], disparo[1]] = "-"

# Realizar dos disparos de prueba
disparo1 = (0, 1)
disparo2 = (5, 5)
disparo(disparo1)
disparo(disparo2)

# Función para generar un nuevo barco de longitud 4 aleatoriamente
def nuevo_barco():
    posicion = (np.random.randint(10), np.random.randint(10))
    orientacion = np.random.randint(0, 4)  # 0->N, 1->S, 2->E, 3->O
    barco_nuevo = []

    # Verificar si hay espacio para posicionar el barco según la orientación
    if orientacion == 0 and posicion[0] >= 3:
        for i in range(4):
            barco_nuevo.append(((posicion[0] - i), posicion[1]))
    elif orientacion == 1 and posicion[0] <= 6:
        for i in range(4):
            barco_nuevo.append(((posicion[0] + i), posicion[1]))
    elif orientacion == 2 and posicion[1] <= 6:
        for i in range(4):
            barco_nuevo.append(((posicion[0]), posicion[1] + i))
    elif orientacion == 3 and posicion[1] >= 3:
        for i in range(4):
            barco_nuevo.append(((posicion[0]), posicion[1] - i))
    else:
        return nuevo_barco()  # Si no hay espacio, generar un nuevo barco

    # Verificar que el nuevo barco no se superponga con los existentes
    for posi_barco_nuevo in barco_nuevo:
        for barco in barcos:
            for posi_barco in barco:
                if posi_barco == posi_barco_nuevo:
                    return nuevo_barco()  # Si se superpone, generar un nuevo barco

    # Imprimir el nuevo barco y posicionarlo en el tablero
    print(barco_nuevo)
    posicionar_barco(barco_nuevo)

# Generar y posicionar un nuevo barco
nuevo_barco()
nuevo_barco()

# Imprimir el estado actual del tablero
print(tablero)



[(6, 5), (6, 6), (6, 7), (6, 8)]
[(9, 0), (8, 0), (7, 0), (6, 0)]
[[' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' 'O' 'O' 'O' 'O' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [264]:
import numpy as np

# Ejemplo 1
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array2_ = np.array([4, 5, 6])


# Usando np.c_ para concatenar a lo largo de las columnas
result1 = np.c_[array1, array2,]
print(array1)
print(array2)
print(array1.shape)
print(result1)
print(result1.shape)
array3 = np.array([[7], [8], [9]])
print(array3)
print(array3.shape)


# Ejemplo 2
array5 = np.array([[7], [8], [9]])

# Usando np.c_ para concatenar a lo largo de las columnas
result2 = np.c_[result1, array5]
print(result2)
print(result2.shape)





[1 2 3]
[4 5 6]
(3,)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[7]
 [8]
 [9]]
(3, 1)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


In [278]:
array1 = np.array([[[1, 2, 3],[1, 2, 3]],[[1, 2, 3],[1, 2, 3]]])
array2 = np.array([[[1, 2],[1, 2]],[[1, 2],[1, 2]]])
print(array1)
print(array1.shape)
print(array2)
print(array2.shape)
print (np.c_[array1,array2])
print (np.c_[array1,array2].shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
(2, 2, 2)
[[[1 2 3 1 2]
  [1 2 3 1 2]]

 [[1 2 3 1 2]
  [1 2 3 1 2]]]
(2, 2, 5)
